In [1]:
import numpy as np

In [2]:
dizi = np.arange(5)

In [3]:
dizi


array([0, 1, 2, 3, 4])

In [4]:
dizi.shape

(5,)

In [8]:
dizi2 = np.array([[0, 1, 2, 3, 4, 5]])

In [9]:
dizi2


array([[0, 1, 2, 3, 4, 5]])

In [10]:
dizi2.shape

(1, 6)

In [11]:
dizi2.shape=3,2

In [12]:
dizi2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
dizi2.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
dizi2.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [19]:
matris1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matris1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
matris1.T # Transpozu alınır.

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [21]:
matris2=np.array([[10,20,30],[40,50,60],[70,80,90]])
matris2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
matris3 = np.concatenate((matris1,matris2)) # iki matrisi birleştirir.

In [24]:
matris3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [26]:
matris3 = np.concatenate((matris1,matris2), axis=1) 
matris3

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60],
       [ 7,  8,  9, 70, 80, 90]])

In [27]:
np.vstack((matris1,matris2)) # v, vertical yani dikey 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [29]:
np.hstack((matris1,matris2)) # h, horizontal yani yatay

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60],
       [ 7,  8,  9, 70, 80, 90]])