In [1]:
import numpy as np


In [3]:
matris =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matris.shape

(3, 3)

In [6]:
matris2=matris

In [7]:
matris2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matris[1,1] = 150

In [12]:
matris

array([[  1,   2,   3],
       [  4, 150,   6],
       [  7,   8,   9]])

In [13]:
matris2

array([[  1,   2,   3],
       [  4, 150,   6],
       [  7,   8,   9]])

In [14]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
m2 = m1.copy()

In [20]:
m1[1,1] = 150

In [21]:
m1

array([[  1,   2,   3],
       [  4, 150,   6],
       [  7,   8,   9]])

In [22]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
m3 = np.arange(0,10,2) # Sıfırdan başla, 10'a kadar 2'şer ilerle

In [24]:
m3

array([0, 2, 4, 6, 8])

In [25]:
m4 = np.arange(5,65,6)

In [26]:
m4

array([ 5, 11, 17, 23, 29, 35, 41, 47, 53, 59])

In [29]:
m5 = np.random.rand(1) # 0 ile 1 arasında 1 tane sayı döndürür.

In [30]:
m5

array([0.14617473])

In [31]:
m5 = np.random.rand(4) # 0 ile 1 arasında 4 tane sayı döndürür.

In [32]:
m5

array([0.99868166, 0.76557936, 0.33594809, 0.90931498])

In [33]:
m6 = np.random.rand(8)*10 # 8 tane sayı döndürür.

In [34]:
m6

array([4.66405478, 3.42911073, 5.23939026, 6.63196219, 1.65952029,
       1.97018548, 8.73794192, 7.60625113])

In [35]:
m7 = np.random.rand(2,2) # 2*2'lik bir matris döndürür.

In [36]:
m7

array([[0.05976378, 0.48633669],
       [0.11307463, 0.94504303]])