In [1]:
import numpy as np

In [2]:
np.linspace(0,10,5) # 0'dan 10'a kadar eşit aralıklı 5 tane sayı döndürür.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
np.linspace(3,29,7)

array([ 3.        ,  7.33333333, 11.66666667, 16.        , 20.33333333,
       24.66666667, 29.        ])

In [4]:
dizi = np.array(["a","b"])

In [5]:
dizi2=np.array(["a","b"])

In [6]:
dizi3=np.array([1,2])

In [7]:
dizi==dizi2

array([ True,  True])

In [8]:
dizi==dizi3

C:\Users\YRG\AppData\Local\Temp\ipykernel_9340\2743472999.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  dizi==dizi3


False

In [9]:
dizi4=np.array(["a",2])

In [10]:
dizi3==dizi4

C:\Users\YRG\AppData\Local\Temp\ipykernel_9340\2670608415.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  dizi3==dizi4


False

In [11]:
dizi==dizi4

array([ True, False])

In [12]:
dizi!=dizi4

array([False,  True])

In [13]:
d1 = np.array([1,2])
d2 = np.array([0,5])

In [14]:
d1<d2

array([False,  True])