In [1]:
import numpy as np

In [2]:
matris = np.array(([1,2,3],[4,5,6],[7,8,9]))
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
matris.size

9

In [4]:
matris.ndim

2

In [5]:
matris.shape

(3, 3)

In [6]:
matris[0,0]

1

In [7]:
matris[2,2]

9

In [8]:
matris[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matris[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [10]:
matris[:1]

array([[1, 2, 3]])

In [11]:
matris[2,1]

8

In [12]:
matris[2,1] = 35

In [13]:
matris[2,1]

35