In [1]:
liste = [1,2,3]


In [2]:
liste

[1, 2, 3]

In [3]:
liste+=1

TypeError: 'int' object is not iterable

In [4]:
import numpy as np

In [5]:
liste2 = np.array(liste)
liste2 +=1

In [6]:
liste

[1, 2, 3]

In [7]:
liste2

array([2, 3, 4])

In [8]:
liste2 = np.array(liste)
liste2+=5

In [9]:
liste2

array([6, 7, 8])

In [10]:
liste2*5

array([30, 35, 40])