In [1]:
import numpy as np 

In [2]:
dizi = np.array(([1,2,3],
                [4,5,6],
                [7,8,9]
               ))
dizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
dizi.min()

1

In [4]:
dizi.max

<function ndarray.max>

In [5]:
dizi.max()

9

In [6]:
dizi.argmin() # Bir fonksiyonun minimum noktası. Dizinin minimum noktası.

0

In [7]:
dizi.sum()

45

In [8]:
dizi.mean() # ortalama alır.

5.0

In [9]:
dizi.mean(axis=1) # satırların ortalaması yani row'ların.

array([2., 5., 8.])

In [10]:
dizi.std() # standart sapmayı hesaplar.

2.581988897471611

In [11]:
dizi.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [12]:
dizi.var() # varyansı hesaplar.

6.666666666666667

In [13]:
dizi.clip(2,5) # Dizideki bütün elemanları bu aralığa çevirir.

array([[2, 2, 3],
       [4, 5, 5],
       [5, 5, 5]])

In [14]:
dizi2=np.random.rand(3,3)*10

In [15]:
dizi2

array([[1.56173771, 6.35297958, 9.59800446],
       [7.41795243, 8.64300886, 5.7534486 ],
       [3.45031448, 1.8988925 , 9.16715822]])

In [16]:
dizi2.round() # Sayıları yuvarlar.

array([[ 2.,  6., 10.],
       [ 7.,  9.,  6.],
       [ 3.,  2.,  9.]])

In [17]:
dizi3=np.random.rand(3,3)*10
dizi3

array([[4.739866  , 2.35042699, 0.3443157 ],
       [8.8464978 , 1.94733782, 6.58538762],
       [9.75330609, 8.35905811, 0.84022488]])

In [18]:
dizi3.round(decimals=2) # virgülden sonraki hassasiyeti ayarlar.

array([[4.74, 2.35, 0.34],
       [8.85, 1.95, 6.59],
       [9.75, 8.36, 0.84]])