In [1]:
import numpy as np


In [2]:
dizi = np.array([[5,15,25],[35,45,55]])
dizi

array([[ 5, 15, 25],
       [35, 45, 55]])

In [3]:
np.sum(dizi) # hepsini toplar.

180

In [4]:
np.prod(dizi) # hepsini çarpar.

162421875

In [5]:
np.sum(dizi[1:,:])

135

In [6]:
np.sum(dizi, axis=1) # axis=1 demek, satırları kendi arasında topla demektir.

array([ 45, 135])

In [7]:
dizi

array([[ 5, 15, 25],
       [35, 45, 55]])

In [8]:
np.sum(dizi, axis=0) # sütunları kendi arasında topla demektir.

array([40, 60, 80])

In [9]:
np.prod(dizi, axis=0)

array([ 175,  675, 1375])